### ISSUE TITLE
CBHC use and TCPGecko

### ISSUE THREAD

**Issue by Qiangong2** [PretendoNetwork/HokakuCafe#1]
I'm currently using HokakuCafe on my Wii U which runs CBHC. Is it possible to make it so that TCPGecko and Hokaku can run at the same time? Specifically, I would like to use this: https://github.com/dmgrstuff/rpcgecko in tandem with Hokaku.

**Comment by GaryOderNichts** [comment]
I don't think there is anything that prevents you from running TCPGecko and HokakuCafe at the same time.
Simply launch HokakuCafe and TCPGecko afterwards.
Or did you run into any issues by doing that?

**Comment by Qiangong2** [comment]
TCPGecko crashes and doesn't launch if you try and run them in that order. It just send you back to the homebrew menu, unable to install it.

**Comment by Qiangong2** [comment]
Tried again after updating TCPGecko with the same result. The Wii U crashes if you load TCPGecko and then try and load Hokaku, but if you load Hokaku first, TCPGecko fails to launch

**Comment by Qiangong2** [comment]
Closing as I've upgraded to Tiramisu
